#!/usr/bin/env python3
"""Generate thin Codex adapters for the canonical Claude project skills."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / ".claude" / "skills"
TARGET_ROOT = ROOT / ".agents" / "skills"
GENERATED_MARKER = "<!-- Generated by scripts/sync-codex-skill-adapters.py; do not edit. -->"


def first_heading(text: str, fallback: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def adapter_description(source_text: str, name: str) -> str:
    title = first_heading(source_text, name)
    return f"AI Berkshire 项目工作流：{title}。"


def adapter_content(name: str, description: str) -> str:
    quoted_name = json.dumps(name, ensure_ascii=False)
    quoted_description = json.dumps(description, ensure_ascii=False)
    return f"""---
name: {quoted_name}
description: {quoted_description}
---

{GENERATED_MARKER}

# Codex adapter: {name}

这是 Codex 的薄入口，不包含研究 workflow 正文。执行前读取仓库根目录的 `AGENTS.md`，
再读取 canonical workflow：`.claude/skills/{name}/SKILL.md`。

遵循 canonical workflow；Claude Code 专属的参数、工具和团队编排语法按 `AGENTS.md` 的
Codex 适配约定转换：
- `$ARGUMENTS` 取当前 Codex 请求及其参数，源文件中的 `/skill-name` 对应 `$skill-name`
  或直接读取对应 canonical 文件。
- `Bash`、`Read`、`Write`、`WebSearch`、`WebFetch`、`Task` 等工具按 `AGENTS.md` 的
  Codex 适配约定转换；并行能力不可用时按 workflow 角色顺序执行并如实说明。
不要把本文件扩展为另一份 workflow。
"""


def source_skills() -> dict[str, tuple[Path, str]]:
    if not SOURCE_ROOT.is_dir():
        raise SystemExit(f"Canonical skill directory not found: {SOURCE_ROOT}")

    result: dict[str, tuple[Path, str]] = {}
    for source in sorted(SOURCE_ROOT.glob("*/SKILL.md")):
        name = source.parent.name
        result[name] = (source, source.read_text(encoding="utf-8"))
    if not result:
        raise SystemExit(f"No canonical skills found under {SOURCE_ROOT}")
    return result


def generated_adapter_dirs() -> set[Path]:
    if not TARGET_ROOT.is_dir():
        return set()
    result: set[Path] = set()
    for candidate in TARGET_ROOT.iterdir():
        target = candidate / "SKILL.md"
        if candidate.is_dir() and target.is_file():
            if GENERATED_MARKER in target.read_text(encoding="utf-8"):
                result.add(candidate)
    return result


def check_adapters(sources: dict[str, tuple[Path, str]]) -> int:
    stale: list[str] = []
    expected_names = set(sources)

    for name, (source, source_text) in sources.items():
        target = TARGET_ROOT / name / "SKILL.md"
        expected = adapter_content(name, adapter_description(source_text, name))
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            stale.append(str(target.relative_to(ROOT)))

    for directory in sorted(generated_adapter_dirs()):
        if directory.name not in expected_names:
            stale.append(str((directory / "SKILL.md").relative_to(ROOT)))

    if stale:
        print("Codex skill adapters are out of date:")
        for path in stale:
            print(f"  {path}")
        return 1

    print(f"Checked {len(sources)} Codex skill adapters in {TARGET_ROOT.relative_to(ROOT)}")
    return 0


def sync_adapters(sources: dict[str, tuple[Path, str]], prune: bool) -> None:
    TARGET_ROOT.mkdir(parents=True, exist_ok=True)

    for name, (source, source_text) in sources.items():
        target_dir = TARGET_ROOT / name
        target_dir.mkdir(parents=True, exist_ok=True)
        target = target_dir / "SKILL.md"
        target.write_text(
            adapter_content(name, adapter_description(source_text, name)),
            encoding="utf-8",
        )

    if prune:
        expected_names = set(sources)
        for directory in generated_adapter_dirs():
            if directory.name not in expected_names:
                shutil.rmtree(directory)

    print(f"Generated {len(sources)} Codex skill adapters in {TARGET_ROOT.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify adapters without writing")
    parser.add_argument(
        "--prune",
        action="store_true",
        help="remove stale adapters previously generated by this script",
    )
    args = parser.parse_args()

    sources = source_skills()
    if args.check:
        return check_adapters(sources)
    sync_adapters(sources, prune=args.prune)
    return 0


if __name__ == "__main__":
    sys.exit(main())
